### ISSUE TITLE
Nome dos métodos de extensão diferentes para o mesmo erro

### ISSUE THREAD

**Issue by aldovrando-oliveira** [cabother/Cabother-Exceptions#7]
Há dois métodos de extensão que estão com os nomes diferentes mas que retornam a mesma exceção

![image](https://user-images.githubusercontent.com/22430116/114817965-51047f00-9d91-11eb-9671-838eb7521957.png)

**Comment by cabother** [comment]
Corrigido e publicado na versão:
 - https://github.com/cabother/Cabother-Exceptions/releases/tag/v1.0.4
